language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t soumi/docker-reactapp -f Dockerfile.dev .

script:
  - docker run  soumi/docker-reactapp npm run test -- --coverage

